### ISSUE TITLE
Failures on Ubuntu 18.04

### ISSUE THREAD

**Issue by bstin** [virt-manager/virt-bootstrap#3]
Hi All. 

Trying to debug an error with my install. 

I am unable to successfully run virt-bootstrap, running this command:

`virt-bootstrap virt-builder://centos-7.5 centos/ --root-password testing --debug`

Produces this error:

`DEBUG remotepath /
DEBUG localdir centos/
Traceback (most recent call last):
  File "/home/b/.local/bin/virt-bootstrap", line 11, in <module>
    load_entry_point('virt-bootstrap==1.1.0', 'console_scripts', 'virt-bootstrap')()
  File "/home/b/.local/lib/python2.7/site-packages/virtBootstrap/virt_bootstrap.py", line 335, in main
    progress_cb=args.status_only)
  File "/home/b/.local/lib/python2.7/site-packages/virtBootstrap/virt_bootstrap.py", line 149, in bootstrap
    progress=prog).unpack(dest)
  File "/home/b/.local/lib/python2.7/site-packages/virtBootstrap/sources/virt_builder_source.py", line 109, in unpack
    g.copy_out('/', dest)
  File "/home/b/.local/lib/python2.7/site-packages/guestfs.py", line 2203, in copy_out
    r = libguestfsmod.copy_out(self._o, remotepath, localdir)
RuntimeError: tar subprocess failed: tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors`

Upon more investigation, I've run `./setup.py test` in virt-bootstrap and get a similar "tar" error below:

```
ERROR: test_dir_extract_rootfs (tests.virt_builder_source.TestVirtBuilderSource)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/b/src/virt-bootstrap/tests/virt_builder_source.py", line 190, in test_dir_extract_rootfs
    self.call_bootstrap()
  File "/home/b/src/virt-bootstrap/tests/virt_builder_source.py", line 182, in call_bootstrap
    root_password=self.root_password
  File "src/virtBootstrap/virt_bootstrap.py", line 149, in bootstrap
    progress=prog).unpack(dest)
  File "src/virtBootstrap/sources/virt_builder_source.py", line 109, in unpack
    g.copy_out('/', dest)
  File "/home/b/.local/lib/python2.7/site-packages/guestfs.py", line 2203, in copy_out
    r = libguestfsmod.copy_out(self._o, remotepath, localdir)
RuntimeError: tar subprocess failed: tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors
```
I'm unsure how to debug this further, any pointers?

**Comment by rst0git** [comment]
Hi @bstin 

I was able to reproduce the issue and it seems to be related to libguestfs. I created a bugzilla report in https://bugzilla.redhat.com/show_bug.cgi?id=1629426

**Comment by bstin** [comment]
@rst0git , Many Thanks. 

I will follow developments on that bugzilla thread.
